### ISSUE TITLE
unable to get popup.location.search

### ISSUE THREAD

**Issue by cisprachidubey** [GenFirst/react-twitter-auth#2] opened 2017-09-18 11:02 UTC
Unable to get popup.location.search , due to which oauth_verifier and oauth_token is not available  and getting this error on the screen , "OAuth redirect has occurred but no query or hash parameters were found.They were either not set during the redirect, or were removed—typically by a routing library—before Twitter react component could read it."

**Comment by ivanvs** [comment] 2017-09-18 19:11
Hi,

I would like to thank you for your feedback. We will investigate issue that you have found. Hopefully we will fix this issue in next release of library. I have an idea how to try to reproduce the issue.

**Comment by ivanvs** [comment] 2017-09-18 20:24
I've managed to reproduce your issue. This should be fixed now. Could you please test new version, v0.0.7?

**Comment by cisprachidubey** [comment] 2017-09-19 09:57
Thanks for quick fix and reply , Had seen another thing. Not sure if it is a bug or what. I can see two request to requestTokenUrl as well as loginUrl. after clicking on twitter login button.
First request gets the result but another request doesn't brings any result.

**Comment by cisprachidubey** [comment] 2017-09-19 14:39
Another thing is , response from loginUrl is not available in the passportJs code , there it is showing some error in the example provided on the repo. 
I am using php as backend , and there i can that values are coming from the twitter, but json response from loginUrl is not parse-able in reactJs, Promise from fetch Ajax api is still pending.

**Comment by ivanvs** [comment] 2017-09-19 20:15
Hi,
I have looked at issue that you report, with two requests fro loginUrl and requestTokenUrl.

![preflight](https://user-images.githubusercontent.com/599231/30612837-2eb44a02-9d86-11e7-9b15-edaf28cadb2f.png)

That is ok. First reqeust is preflight request and is needed for CORS. You can find little bit more information about that [here](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request)

About second issue, Promise from fetch Ajax api is still pending, that should not happening. I am testing on example code that is in this repository, and I don't have any issues. Have you changed anything? Do you have some errors in console in which you are running project?

If you look at example code, I had to transform a little bit response from twitter, because response from Twitter API is not JSON. So I have done this:

`const bodyString = '{ "' + body.replace(/&/g, '", "').replace(/=/g, '": "') + '"}';`

Body has looked like this:

`oauth_token=7588892-kagSNqWge8gB1WwE3plnFsJHAZVfxWD7Vb57p0b4&
oauth_token_secret=PbKfYqSryyeKDWz4ebtY3o5ogNLG11WJuZBc9fQrQo`

and from that I have created JSON object with that transformation:
`{
  "oauth_token": "7588892-kagSNqWge8gB1WwE3plnFsJHAZVfxWD7Vb57p0b4",
  "oauth_token_secret": "PbKfYqSryyeKDWz4ebtY3o5ogNLG11WJuZBc9fQrQo"
}`

The whole process of login is documented in [Twitter documentation](https://dev.twitter.com/web/sign-in/implementing).

I am very glad that you have interest in this library :+1:

**Comment by cisprachidubey** [comment] 2017-09-20 06:23
Haven't did any change in code , just installed your example. and executed it and found this error in console. Hope it will help..

InternalOAuthError: Failed to fetch user profile
    at /var/www/html/react-twitter-auth/example/backend/node_modules/passport-twitter-token/lib/index.js:141:32
    at passBackControl (/var/www/html/react-twitter-auth/example/backend/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/var/www/html/react-twitter-auth/example/backend/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ivanvs** [comment] 2017-09-20 09:05
Have you replace KEY and SECRET with key and secret of your Twitter application. You have to change that in [passport.js](https://github.com/GenFirst/react-twitter-auth/blob/master/example/backend/passport.js) and in two places in [server.js](https://github.com/GenFirst/react-twitter-auth/blob/master/example/backend/server.js) file?

Also your Twitter application should be able to read user email. That could be enabled in Permissions tab of Twitter application settings.

**Comment by cisprachidubey** [comment] 2017-09-21 07:30
Yes , i had kept my keys in server.js , but missed to set in passport.js . Thanks , had kept it there as well. 
But again the problem persists. It has saved user in my database. That is good. 
But it haven't sent anything to client side. In onSuccess function on clinet side it prints nothing. it supposed to send some success msg along with registered user data. But console.log print only empty object {} . It must return something there so that we would able to create login session/cookies on react.
![screenshot from 2017-09-21 12 58 06](https://user-images.githubusercontent.com/31987808/30683841-91eb606e-9ecc-11e7-8b1e-080e4c833265.png)

**Comment by ivanvs** [comment] 2017-09-21 08:16
You are totally right. I will fix this when I finish my job. As I see in picture, you are getting response from server, but it is not printed correctly. So it just need to be printed correctly, and I will improve that in example.

Thank you for feedback  👍

**Comment by ivanvs** [comment] 2017-09-21 19:26
I have improved example so that `onSuccess` handler shows nicely response content:
```
onSuccess(response) {
    response.json().then(body => {
      alert(JSON.stringify(body));
    });
  }
}
```

`response` is response object from [fetch](https://github.com/github/fetch) library. I have decided to call `onSuccess` handler with full object so that if users have some headers in response they could get that headers easily.

I have refactored a little bit backend example, so that now key and secret for twitter application are extracted in separate file. So that nobody else has the same problem as you had yesterday.

**Comment by cisprachidubey** [comment] 2017-09-22 11:12
Thanks for the update , your example works. But here i am facing very strange problem. As you explained me earlier that fetch method sends two request , On node example it returns with 204 status for one and 200 for another. But when i send same request to a php files, return status of both request is 200. and response of last request is blank. Do you have any idea about this.
![screenshot](https://user-images.githubusercontent.com/31987808/30742019-f770f7ee-9fb4-11e7-9712-6dd90791e501.png)

**Comment by ivanvs** [comment] 2017-09-22 13:27
Hi, if you are hosting your client application on same server and domain as your backend then you don't need CORS, and then there will not be preflight requests. 

But I am not sure why you are getting two requests for oauth_verifier, then. Could you tell me what framework/libraries you are using? I could check documentation and see if I could figure out what is the issue. I have never worked with php, but I could try to figure out what is the issue.

**Comment by cisprachidubey** [comment] 2017-09-25 06:47
Hi , Thanks for the help. had managed to get the response. By making few changes in my php. In my php code , OPTION request is also being sent to twitter. therefore actual call's response remains empty as token was already got used in first call. so i had made a check to do nothing if request type is OPTION.

Rather there is a small suggestion , in your plugin there is a small icon of twitter is used. I guess there should be privilege to either change the image or to keep that image unused. In my case do not want to use any image on twitter login button. So Image use should be optional. It would be great if you can provide that option as well. :) 

Thanks again for all your help.

**Comment by ivanvs** [comment] 2017-09-25 08:35
Hi, great suggestion, I will implement this and then publish new version on npm.

I am very glad to here that you have managed to fix your issue.

**Comment by ivanvs** [comment] 2017-09-25 22:45
Hi I have released version 0.0.8. You should be able to hide default twitter icon without any problem.
```
 <TwitterLogin loginUrl="http://localhost:4000/api/v1/auth/twitter"
                      onFailure={this.onFailed}
                      onSuccess={this.onSuccess}
                      requestTokenUrl="http://localhost:4000/api/v1/auth/twitter/reverse"
showIcon={true}/>
```
The whole button can be styled with `style` property.

I have improved documentation a little bit :)

I was also thinking to support of customization of icon, but it is very late here, so I will left that for some other time. 

Could you please test this change and give me feedback?

**Comment by cisprachidubey** [comment] 2017-09-26 12:28
It works Great, Thanks for considering my request :)

**Comment by ivanvs** [comment] 2017-09-26 13:15
I will close this issue. 

If you have any further problems, please do not hesitate to create a new issue. 

Thank you for your valuable feedback.

**Closed** 2017-09-26 20:07 UTC
Labels: bug

**Comment by cisprachidubey** [comment] 2017-10-07 07:38
Hello , 

Do there is a way to implement Twitter login without making any server side call , I mean is there any twitter's javascript SDK is available as of Facebook?
For facebook login we dont have to write code on server side , javascript sdk of facebook does that automatically.

**Comment by ivanvs** [comment] 2017-10-07 09:54
Hi.

As far as I am aware, Twitter doesn't have JavaScript SDK. Also Twitter implements OAuth 1.0, where Facebook implements OAuth 2.0.

Through, Twitter documentation I haven't managed to find solution that would not include change of server. If you manage to find different flow for authorization, feel free to send me documentation and I will do my best to support it in this component.

**Comment by cisprachidubey** [comment] 2017-11-06 10:49
Hello Ivanvs,

I wondering that could we have ability to send some data alongwith requestTokenUrl and loginUrl, In my case i am utilising an API  on server side, which checks for some keys which should be posted with the url. If those keys is not present My api is not allowing it to access the method.

**Comment by ivanvs** [comment] 2017-11-06 17:35
Hi,

Could you please open new issue for this problem. 

I understand your requirements, and I will try to add that to next release. Most likely I will add another property for additional headers.

Just open the new issue, please.

**Comment by cisprachidubey** [comment] 2017-11-07 06:49
sure

**Comment by JothsnaR** [comment] 2020-01-21 06:08
Unable to get popup.location.search , due to which oauth_verifier and oauth_token is not available and getting this error on the screen , "OAuth redirect has occurred but no query or hash parameters were found.They were either not set during the redirect, or were removed—typically by a routing library—before Twitter react component could read it." 

I am facing this issue in v0.0.13 can someone please help me with this
