### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Tremus** [GenFirst/react-twitter-auth#16] opened 2018-02-21 12:32 UTC
I'm using basically the boilerplate from the README and getting a syntax error
```
<TwitterLogin
    loginUrl="http://localhost:8080/accounts/twitter/login/"
    onFailure={this.onFailed}
    onSuccess={this.onSuccess}
    requestTokenUrl="http://localhost:8080/accounts/twitter/login/callback/"
/>
```
Here's the stack from Chrome's Dev Tools _Network_:

getRequestToken | @ | react-twitter-auth-component.js:372
-- | -- | --
onButtonClick | @ | react-twitter-auth-component.js:356
callCallback | @ | react-dom.development.js:542
invokeGuardedCallbackDev | @ | react-dom.development.js:581
invokeGuardedCallback | @ | react-dom.development.js:438
invokeGuardedCallbackAndCatchFirstError | @ | react-dom.development.js:452
executeDispatch | @ | react-dom.development.js:836
executeDispatchesInOrder | @ | react-dom.development.js:858
executeDispatchesAndRelease | @ | react-dom.development.js:956
executeDispatchesAndReleaseTopLevel | @ | react-dom.development.js:967
forEachAccumulated | @ | react-dom.development.js:935
processEventQueue | @ | react-dom.development.js:1112
runEventQueueInBatch | @ | react-dom.development.js:3607
handleTopLevel | @ | react-dom.development.js:3616
handleTopLevelImpl | @ | react-dom.development.js:3347
batchedUpdates | @ | react-dom.development.js:11082
batchedUpdates | @ | react-dom.development.js:2330
dispatchEvent | @ | react-dom.development.js:3421

Looks like it may be an issue where the header is set to html rather than `Content-Type:application/json`. Any clue on where the issue lies/how to fix this?

**Comment by ivanvs** [comment] 2018-02-21 20:55
Have you put appropriate Twitter key and secret? I had similar issue when i put a space in front of my Twitter key. Could you check if there is some error on backend?

I will check application again, but it would be nice if you could send me this informations.

**Comment by khteh** [comment] 2018-02-22 08:44
The problem was due to the fact that I didn't implement the server....

**Comment by ivanvs** [comment] 2018-02-22 09:38
@khteh have you missed the thread?

**Comment by khteh** [comment] 2018-02-22 09:40
What do you mean? I tried the client without the server. So, I assume that's the cause of the problem I saw.

**Comment by ivanvs** [comment] 2018-02-22 09:50
ok, great to hear that you find out what was the issue.

**Comment by khteh** [comment] 2018-02-22 09:59
Close this

**Closed** 2018-04-24 14:19 UTC

**Comment by Tremus** [comment] 2018-04-27 05:26
Sorry, I got sidetracked and forgot  to report back here. Yes, it was an error coming from my **server**, not a problem with _react-twitter-auth_

**Comment by mreshnaan** [comment] 2022-08-02 18:10
hey my backend works fine but i shows the error

**Comment by mreshnaan** [comment] 2022-08-02 18:11
![Screenshot_175](https://user-images.githubusercontent.com/63632473/182444579-78f43eae-e1df-4c3b-b191-4c8967115b04.png)
